.TH OPENSPACE 1 "August 2025" "OpenSpace 0.21.2"
.SH NAME
openspace \- interactive data visualization tool for astronomy
.SH SYNOPSIS
.B openspace
[\fIoptions\fR]
.SH DESCRIPTION
OpenSpace is an open-source interactive data visualization tool designed
to visualize the entire known universe and portray our ongoing efforts
to explore the cosmos.
.SH OPTIONS
Run
.B openspace --help
for a list of available command-line options.
.SH RESOURCES
Documentation is available online:
.UR https://docs.openspaceproject.com/
.UE
.SH AUTHOR
The OpenSpace team <info@openspaceproject.com>
