#Version
12.13

#Property
setPropertyValue	property_name_1	property_value_1
setPropertyValue	property_name_2	property_value_2
setPropertyValue	property_name_3	property_value_3
setPropertyValueSingle	property_name_4	property_value_5
setPropertyValueSingle	property_name_4	property_value_5
setPropertyValueSingle	property_name_4	property_value_5
