contact_links:
  - name: Slack Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here. Slack is the easiest and most reliable way of getting in touch with the project members.
