
// This file has been auto-generated by the codegen tool by running codegen either
// directly or indirectly on:  staticrotation.cpp
//
// Do not change this file manually as any change will be automatically overwritten,
// instead change the struct tagged with "codegen::Dictionary" in the main file from which
// the code in this file was generated.
//
// If a compiler error brought you here, a struct tagged with "codegen::Dictionary"
// was changed without the codegen tool being run again.

namespace codegen {
template <typename T> openspace::documentation::Documentation doc() {
    static_assert(sizeof(T) == 0); // This should never be called
    return openspace::documentation::Documentation();
}
template <> openspace::documentation::Documentation doc<openspace::StaticRotation>() {
    using namespace openspace::documentation;
    TableVerifier* codegen_Parameters = new TableVerifier;
    codegen_Parameters->documentations.push_back({"Rotation",new OrVerifier({new DoubleVector3Verifier,new DoubleVector4Verifier,new DoubleMatrix3x3Verifier,}),Optional::No,"Stores the static rotation as a vector containing Euler angles, a quaternion or a rotation matrix"});

    openspace::documentation::Documentation d = {
        "StaticRotation",
        "StaticRotation",
        std::move(codegen_Parameters->documentations)
    };
    delete codegen_Parameters;
    return d;
}
} // namespace codegen


namespace codegen {
namespace internal {
template<typename T> void bakeTo(const ghoul::Dictionary&, std::string_view, T*) { static_assert(sizeof(T) == 0); } // This should never be called
void bakeTo(const ghoul::Dictionary& d, std::string_view key, glm::dmat3x3* val) { *val = d.value<glm::dmat3x3>(key); }
void bakeTo(const ghoul::Dictionary& d, std::string_view key, glm::dvec3* val) { *val = d.value<glm::dvec3>(key); }
void bakeTo(const ghoul::Dictionary& d, std::string_view key, glm::dvec4* val) { *val = d.value<glm::dvec4>(key); }
void bakeTo(const ghoul::Dictionary& d, std::string_view key, std::variant<glm::dvec3, glm::dvec4, glm::dmat3x3>* val) {
   if (d.hasValue<glm::dvec3>(key)) { glm::dvec3 v; bakeTo(d, key, &v); *val = std::move(v); }
   if (d.hasValue<glm::dvec4>(key)) { glm::dvec4 v; bakeTo(d, key, &v); *val = std::move(v); }
   if (d.hasValue<glm::dmat3x3>(key)) { glm::dmat3x3 v; bakeTo(d, key, &v); *val = std::move(v); }
}
} // namespace internal

template <typename T> T bake(const ghoul::Dictionary&) { static_assert(sizeof(T) == 0); }
template <> Parameters bake<Parameters>(const ghoul::Dictionary& dict) {
    openspace::documentation::testSpecificationAndThrow(codegen::doc<openspace::StaticRotation>(), dict, "StaticRotation");
    Parameters res;
    internal::bakeTo(dict, "Rotation", &res.rotation);
    return res;
}
} // namespace codegen
