--openspace.setPropertyValue('Earth.renderable.colorTexture', '${OPENSPACE_DATA}/modules/mars/textures/mars.png')
openspace.time.setTime("2005-11-01T00:00:00")
openspace.time.setDeltaTime(200000.0)
--openspace.time.setDeltaTime(30000.0)
print(openspace.time.currentTimeUTC())
