
// This file has been auto-generated by the codegen tool by running codegen either
// directly or indirectly on:  A:\OpenSpace\modules\base\dashboard\dashboarditemangle.cpp
//
// Do not change this file manually as any change will be automatically overwritten,
// instead change the struct tagged with "codegen::Dictionary" in the main file from which
// the code in this file was generated.
//
// If a compiler error brought you here, a struct tagged with "codegen::Dictionary"
// was changed without the codegen tool being run again.

namespace codegen {
template <typename T> openspace::documentation::Documentation doc() {
    static_assert(sizeof(T) == 0); // This should never be called
}
template <> openspace::documentation::Documentation doc<openspace::DashboardItemAngle>() {
    using namespace openspace::documentation;
    TableVerifier* codegen_Parameters = new TableVerifier;
    codegen_Parameters->documentations.push_back({"SourceType",new StringInListVerifier({"Node", "Focus", "Camera"}),Optional::Yes,SourceTypeInfo.description});
    codegen_Parameters->documentations.push_back({"SourceNodeName",new StringVerifier,Optional::Yes,SourceNodeNameInfo.description});
    codegen_Parameters->documentations.push_back({"ReferenceType",new StringInListVerifier({"Node", "Focus", "Camera"}),Optional::No,ReferenceTypeInfo.description});
    codegen_Parameters->documentations.push_back({"ReferenceNodeName",new StringVerifier,Optional::Yes,ReferenceNodeNameInfo.description});
    codegen_Parameters->documentations.push_back({"DestinationType",new StringInListVerifier({"Node", "Focus", "Camera"}),Optional::Yes,DestinationTypeInfo.description});
    codegen_Parameters->documentations.push_back({"DestinationNodeName",new StringVerifier,Optional::Yes,DestinationNodeNameInfo.description});

    openspace::documentation::Documentation d = {
        "DashboardItemAngle",
        "DashboardItemAngle",
        std::move(codegen_Parameters->documentations)
    };
    delete codegen_Parameters;
    return d;
}
} // namespace codegen


namespace codegen {
namespace internal {
template<typename T> void bakeTo(const ghoul::Dictionary&, std::string_view, T*) { static_assert(sizeof(T) == 0); } // This should never be called

template<typename T> void bakeTo(const ghoul::Dictionary& d, std::string_view key, std::optional<T>* val) {
    if (d.hasKey(key)) {
        T v;
        bakeTo(d, key, &v);
        *val = v;
    }
    else *val = std::nullopt;
}
void bakeTo(const ghoul::Dictionary& d, std::string_view key, std::string* val) { *val = d.value<std::string>(key); }

} // namespace internal

template <typename T> T bake(const ghoul::Dictionary& dict) { static_assert(sizeof(T) == 0); };
template <> Parameters bake<Parameters>(const ghoul::Dictionary& dict) {
    openspace::documentation::testSpecificationAndThrow(codegen::doc<openspace::DashboardItemAngle>(), dict, "DashboardItemAngle");
    Parameters res;
    internal::bakeTo(dict, "SourceType", &res.sourceType);
    internal::bakeTo(dict, "SourceNodeName", &res.sourceNodeName);
    internal::bakeTo(dict, "ReferenceType", &res.referenceType);
    internal::bakeTo(dict, "ReferenceNodeName", &res.referenceNodeName);
    internal::bakeTo(dict, "DestinationType", &res.destinationType);
    internal::bakeTo(dict, "DestinationNodeName", &res.destinationNodeName);
    return res;
}
} // namespace codegen
